# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_column='uprEmail', default='', max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(db_column='uprName', default='', max_length=90)),
                ('push_token', models.CharField(db_column='uprPushToken', default='', max_length=255)),
                ('date_joined', models.DateTimeField(blank=True, db_column='uprDataJoined', default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_column='uprIsActive', default=True)),
                ('is_admin', models.BooleanField(db_column='uprIsAdmin', default=False)),
                ('login_with', models.CharField(blank=True, db_column='useLoginWith', max_length=11, null=True)),
                ('image', models.ImageField(blank=True, db_column='uprImgSrc', null=True, upload_to='user-img')),
            ],
            options={
                'db_table': 'UserProfile',
                'managed': True,
            },
        ),
    ]
