# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='push_token',
        ),
    ]
