# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0002_remove_userprofile_push_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('id', models.AutoField(db_column='askId', primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='askText')),
                ('asked_at', models.DateTimeField(blank=True, db_column='askAskedDate', default=django.utils.timezone.now)),
                ('asked_by', models.ForeignKey(db_column='askAskedBy', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudo_portatil.UserProfile')),
            ],
            options={
                'db_table': 'Ask',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='catId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='catName', max_length=255)),
                ('parent', models.ForeignKey(blank=True, db_column='catParentId', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudo_portatil.Category')),
            ],
            options={
                'db_table': 'Category',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ask',
            name='category',
            field=models.ForeignKey(db_column='askCatId', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudo_portatil.Category'),
        ),
    ]
