# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0003_auto_20161126_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wording',
            fields=[
                ('id', models.AutoField(db_column='worId', primary_key=True, serialize=False)),
                ('text', models.TextField(db_column='worText')),
                ('written_at', models.DateTimeField(blank=True, db_column='worAskedDate', default=django.utils.timezone.now)),
                ('category', models.ForeignKey(db_column='worCatId', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudo_portatil.Category')),
                ('written_by', models.ForeignKey(db_column='worAskedBy', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudo_portatil.UserProfile')),
            ],
            options={
                'db_table': 'Wording',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='ask',
            name='asked_by',
        ),
        migrations.RemoveField(
            model_name='ask',
            name='category',
        ),
        migrations.DeleteModel(
            name='Ask',
        ),
    ]
