# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0005_auto_20161127_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wording',
            name='title',
            field=models.CharField(db_column='worTitle', default='', max_length=255),
        ),
    ]
