# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0006_auto_20161127_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wording',
            name='suport_text',
            field=models.URLField(blank=True, db_column='worSuportText', null=True),
        ),
    ]
