# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0007_auto_20161127_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(db_column='corId', primary_key=True, serialize=False)),
                ('corrected_at', models.DateTimeField(blank=True, db_column='corCorrectedAt', default=django.utils.timezone.now)),
                ('corrected_by', models.ForeignKey(db_column='corCorrectedBy', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudo_portatil.UserProfile')),
                ('wording', models.ForeignKey(db_column='corWorId', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudo_portatil.Wording')),
            ],
            options={
                'db_table': 'Correction',
                'managed': True,
            },
        ),
    ]
