# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0008_correction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_column='citId', null=True)),
                ('text', models.TextField(db_column='citText')),
                ('correction', models.ForeignKey(db_column='citCorId', null=True, on_delete=django.db.models.deletion.CASCADE, to='estudo_portatil.Correction')),
            ],
            options={
                'db_table': 'CorrectionItem',
                'managed': True,
            },
        ),
    ]
