# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0009_correctionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wording',
            name='score',
            field=models.IntegerField(db_column='worScore', null=True),
        ),
    ]
