# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0011_auto_20161127_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctionitem',
            old_name='text',
            new_name='item_text',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ano_letivo',
            field=models.CharField(db_column='uprAnoLetivo', default='', max_length=90),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bairro',
            field=models.CharField(db_column='uprBairro', default='', max_length=90),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='curso',
            field=models.CharField(db_column='uprCurso', default='', max_length=90),
        ),
    ]
