# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0012_auto_20161127_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='curso',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='escola',
            field=models.CharField(db_column='uprEscola', default='', max_length=90),
        ),
    ]
