# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-15 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0013_auto_20161127_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fb_id',
            field=models.IntegerField(db_column='uprFbIf', default=False),
        ),
    ]
