# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-15 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudo_portatil', '0014_userprofile_fb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='fb_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_id',
            field=models.BigIntegerField(db_column='uprFbIf', default=False),
        ),
    ]
